# Generated by Django 5.2 on 2025-04-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('title', models.CharField(max_length=150)),
                ('packet_namber', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('postanova', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['packet_namber'],
            },
        ),
    ]
