# Generated by Django 5.2 on 2025-04-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmgapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='postanova',
            field=models.TextField(null=True),
        ),
    ]
