# Generated by Django 5.2 on 2025-04-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmgapp', '0002_alter_packet_postanova'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packet',
            options={'ordering': ['packet_number']},
        ),
        migrations.RenameField(
            model_name='packet',
            old_name='packet_namber',
            new_name='packet_number',
        ),
    ]
