# Generated by Django 5.2 on 2025-04-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmgapp', '0003_alter_packet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='vymohy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='packet',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
