# Generated by Django 5.2 on 2025-04-16 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmgapp', '0004_packet_vymohy_packet_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablytsySpivstavleny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posluga', models.TextField()),
                ('nk25', models.TextField(null=True)),
                ('nk26', models.TextField(null=True)),
                ('dodatoc', models.TextField(null=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spivstavlennya', to='pmgapp.packet')),
            ],
            options={
                'ordering': ['packet', 'posluga'],
            },
        ),
    ]
