databases:
  - name: pmgdb
    plan: free
    databaseName: pmg 
services:
  - type: web
    plan: free
    name: pmg-web  # Змініть назву вебсервісу, якщо бажаєте
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn pmg.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pmgdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4